Neat = require 'neat'
Neat.require 'core'

require './helpers/geomjs/point_helper'
require './helpers/geomjs/matrix_helper'
require './helpers/geomjs/geometry_helper'
require './helpers/geomjs/surface_helper'
require './helpers/geomjs/path_helper'
require './helpers/geomjs/rectangle_helper'
require './helpers/geomjs/triangle_helper'
require './helpers/geomjs/circle_helper'
require './helpers/geomjs/ellipsis_helper'
require './helpers/geomjs/diamond_helper'
