// Generated by CoffeeScript 1.4.0
(function() {
  var Cloneable, Mixin,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Mixin = require('./mixin');

  Cloneable = (function(_super) {

    __extends(Cloneable, _super);

    function Cloneable() {
      return Cloneable.__super__.constructor.apply(this, arguments);
    }

    Cloneable.included = function(klass) {
      return klass.prototype.clone = function() {
        return new klass(this);
      };
    };

    return Cloneable;

  })(Mixin);

  module.exports = Cloneable;

}).call(this);
