// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var animate, animated, canvas, circle, context, cubicBezier, cubicBezierPoints, diamond, ellipsis, geometries, initUI, linearSpline, linearSplinePoints, mouseX, mouseY, options, polygon, pt, quadBezier, quadBezierPoints, quintBezier, rectangle, render, requestAnimationFrame, spiral, stats, t, testers, triangle;
    stats = new Stats;
    stats.setMode(0);
    $('#canvas').prepend(stats.domElement);
    requestAnimationFrame = window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame || window.oRequestAnimationFrame || window.requestAnimationFrame || function(f) {
      return setTimeout(f, 1000 / 60);
    };
    canvas = $('canvas');
    context = canvas[0].getContext('2d');
    animated = false;
    geometries = [new geomjs.Rectangle(250, 40, 180, 100, Math.PI / 7), new geomjs.Triangle(new geomjs.Point(100, 80), new geomjs.Point(320, 120), new geomjs.Point(140, 200)), new geomjs.Circle(60, 80, 160), new geomjs.Ellipsis(120, 60, 470, 180, 10), new geomjs.Diamond(50, 100, 60, 40, 420, 250), new geomjs.Polygon([new geomjs.Point(160, 190), new geomjs.Point(200, 280), new geomjs.Point(260, 260), new geomjs.Point(280, 280), new geomjs.Point(380, 190), new geomjs.Point(180, 160), new geomjs.Point(260, 220)]), new geomjs.LinearSpline([new geomjs.Point(260, 290), new geomjs.Point(300, 380), new geomjs.Point(320, 300), new geomjs.Point(340, 380), new geomjs.Point(380, 290)]), new geomjs.CubicBezier([new geomjs.Point(120, 300), new geomjs.Point(100, 350), new geomjs.Point(280, 420), new geomjs.Point(120, 420), new geomjs.Point(40, 420), new geomjs.Point(100, 240), new geomjs.Point(180, 200)]), new geomjs.QuadBezier([new geomjs.Point(180, 350), new geomjs.Point(220, 290), new geomjs.Point(260, 350), new geomjs.Point(300, 410), new geomjs.Point(360, 350)]), new geomjs.QuintBezier([new geomjs.Point(380, 350), new geomjs.Point(420, 290), new geomjs.Point(460, 340), new geomjs.Point(500, 290), new geomjs.Point(560, 350)]), new geomjs.Spiral(120, 60, 3, 470, 420, 10, 120)];
    options = {
      bounds: true,
      path: true,
      surface: true,
      angle: true,
      intersections: true,
      vertices: true,
      triangles: true
    };
    testers = geometries.map(function(g) {
      var tester;
      tester = new Tester(g, options);
      options[tester.name] = true;
      return tester;
    });
    t = new Date().valueOf();
    mouseX = 0;
    mouseY = 0;
    render = function() {
      var a, g1, g2, intersection, intersections, tested, _i, _j, _k, _len, _len1, _len2, _results;
      context.fillStyle = '#042029';
      context.fillRect(0, 0, canvas.width(), canvas.height());
      testers.forEach(function(t) {
        t.isOver(mouseX, mouseY);
        if (options[t.name]) {
          return t.render(context);
        }
      });
      if (options.intersections) {
        intersections = [];
        tested = {};
        for (_i = 0, _len = geometries.length; _i < _len; _i++) {
          g1 = geometries[_i];
          if (!options[g1.classname().toLowerCase()]) {
            continue;
          }
          for (_j = 0, _len1 = geometries.length; _j < _len1; _j++) {
            g2 = geometries[_j];
            if (!options[g2.classname().toLowerCase()]) {
              continue;
            }
            if (g1 === g2) {
              continue;
            }
            if (tested[g2 + g1]) {
              continue;
            }
            a = g1.intersections(g2);
            if (a != null) {
              intersections = intersections.concat(a);
            }
            tested[g1 + g2] = true;
          }
        }
        context.fillStyle = '#ffffff';
        _results = [];
        for (_k = 0, _len2 = intersections.length; _k < _len2; _k++) {
          intersection = intersections[_k];
          _results.push(context.fillRect(intersection.x - 2, intersection.y - 2, 4, 4));
        }
        return _results;
      }
    };
    rectangle = geometries[0], triangle = geometries[1], circle = geometries[2], ellipsis = geometries[3], diamond = geometries[4], polygon = geometries[5], linearSpline = geometries[6], cubicBezier = geometries[7], quadBezier = geometries[8], quintBezier = geometries[9], spiral = geometries[10];
    linearSplinePoints = (function() {
      var _i, _len, _ref, _results;
      _ref = linearSpline.vertices;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pt = _ref[_i];
        _results.push(pt.clone());
      }
      return _results;
    })();
    cubicBezierPoints = (function() {
      var _i, _len, _ref, _results;
      _ref = cubicBezier.vertices;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pt = _ref[_i];
        _results.push(pt.clone());
      }
      return _results;
    })();
    quadBezierPoints = (function() {
      var _i, _len, _ref, _results;
      _ref = quadBezier.vertices;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pt = _ref[_i];
        _results.push(pt.clone());
      }
      return _results;
    })();
    animate = function(n) {
      var d;
      if (isNaN(n)) {
        n = new Date().valueOf();
      }
      stats.begin();
      d = n - t;
      t = n;
      t = t / 1000;
      d = d / 100000;
      testers.forEach(function(t) {
        if (options[t.name]) {
          return t.animate(d);
        }
      });
      render();
      if (animated) {
        requestAnimationFrame(animate);
      }
      return stats.end();
    };
    initUI = function() {
      var checkboxes, play;
      canvas.mousemove(function(e) {
        mouseX = e.pageX - canvas.offset().left;
        return mouseY = e.pageY - canvas.offset().top;
      });
      checkboxes = $('input[type=checkbox]').widgets();
      checkboxes.forEach(function(checkbox) {
        return checkbox.valueChanged.add(function(w, v) {
          options[w.jTarget.attr('id')] = v;
          return render();
        });
      });
      play = $('input[type=button]').widgets()[0];
      return play.action = {
        action: function() {
          if (!$('#canvas .hint').hasClass('clicked')) {
            $('#canvas .hint').addClass('clicked');
          }
          if (!animated) {
            t = new Date().valueOf();
            requestAnimationFrame(animate);
            animated = true;
            play.set('value', 'Pause');
            return play.removeClasses('green');
          } else {
            animated = false;
            play.set('value', 'Play');
            return play.addClasses('green');
          }
        }
      };
    };
    initUI();
    render();
    return $('body').removeClass('preload');
  });

}).call(this);
