// Generated by CoffeeScript 1.4.0
(function() {
  var CubicBezier, Formattable, Geometry, Intersections, Path, Point, Sourcable, Spline, include;

  include = require('./include').include;

  Point = require('./point');

  Formattable = require('./mixins/formattable');

  Sourcable = require('./mixins/sourcable');

  Intersections = require('./mixins/intersections');

  Geometry = require('./mixins/geometry');

  Spline = require('./mixins/spline');

  Path = require('./mixins/path');

  CubicBezier = (function() {

    include([Formattable('CubicBezier'), Sourcable('geomjs.CubicBezier', 'vertices', 'bias'), Geometry, Path, Intersections, Spline(3)])["in"](CubicBezier);

    function CubicBezier(vertices, bias) {
      if (bias == null) {
        bias = 20;
      }
      this.initSpline(vertices, bias);
    }

    CubicBezier.prototype.pointInSegment = function(t, seg) {
      var pt;
      pt = new Point();
      pt.x = (seg[0].x * this.b1(t)) + (seg[1].x * this.b2(t)) + (seg[2].x * this.b3(t)) + (seg[3].x * this.b4(t));
      pt.y = (seg[0].y * this.b1(t)) + (seg[1].y * this.b2(t)) + (seg[2].y * this.b3(t)) + (seg[3].y * this.b4(t));
      return pt;
    };

    CubicBezier.prototype.b1 = function(t) {
      return (1 - t) * (1 - t) * (1 - t);
    };

    CubicBezier.prototype.b2 = function(t) {
      return 3 * t * (1 - t) * (1 - t);
    };

    CubicBezier.prototype.b3 = function(t) {
      return 3 * t * t * (1 - t);
    };

    CubicBezier.prototype.b4 = function(t) {
      return t * t * t;
    };

    return CubicBezier;

  })();

  module.exports = CubicBezier;

}).call(this);
