// Generated by CoffeeScript 1.4.0
(function() {
  var Cloneable, Diamond, Equatable, Formattable, Geometry, Intersections, Parameterizable, Path, Point, Surface;

  Point = require('./point');

  Equatable = require('./mixins/equatable');

  Formattable = require('./mixins/formattable');

  Cloneable = require('./mixins/cloneable');

  Parameterizable = require('./mixins/parameterizable');

  Geometry = require('./mixins/geometry');

  Surface = require('./mixins/surface');

  Path = require('./mixins/path');

  Intersections = require('./mixins/intersections');

  Diamond = (function() {
    var PROPERTIES;

    PROPERTIES = ['x', 'y', 'top', 'left', 'bottom', 'right'];

    Formattable.apply(Formattable, ['Diamond'].concat(PROPERTIES)).attachTo(Diamond);

    Parameterizable('diamondFrom', {
      top: 1,
      right: 1,
      bottom: 1,
      left: 1,
      x: 0,
      y: 0,
      rotation: 0
    }).attachTo(Diamond);

    Equatable.apply(Equatable, PROPERTIES).attachTo(Diamond);

    Cloneable.attachTo(Diamond);

    function Diamond(top, right, bottom, left, x, y, rotation) {
      var args;
      args = this.diamondFrom(top, right, bottom, left, x, y, rotation);
      this.top = args.top, this.right = args.right, this.bottom = args.bottom, this.left = args.left, this.x = args.x, this.y = args.y, this.rotation = args.rotation;
    }

    return Diamond;

  })();

  module.exports = Diamond;

}).call(this);
