// Generated by CoffeeScript 1.4.0
(function() {
  var Formattable, Geometry, Intersections, LinearSpline, Path, Point, Sourcable, Spline;

  Point = require('./point');

  Formattable = require('./mixins/formattable');

  Sourcable = require('./mixins/sourcable');

  Intersections = require('./mixins/intersections');

  Geometry = require('./mixins/geometry');

  Spline = require('./mixins/spline');

  Path = require('./mixins/path');

  LinearSpline = (function() {

    Formattable('LinearSpline').attachTo(LinearSpline);

    Sourcable('geomjs.LinearSpline', 'vertices', 'bias').attachTo(LinearSpline);

    Geometry.attachTo(LinearSpline);

    Path.attachTo(LinearSpline);

    Intersections.attachTo(LinearSpline);

    Spline(1).attachTo(LinearSpline);

    function LinearSpline(vertices, bias) {
      this.initSpline(vertices, bias);
    }

    LinearSpline.prototype.points = function() {
      return this.vertices.concat();
    };

    LinearSpline.prototype.segments = function() {
      return this.vertices.length - 1;
    };

    LinearSpline.prototype.validateVertices = function(vertices) {
      return vertices.length >= 2;
    };

    LinearSpline.prototype.fill = function() {};

    LinearSpline.prototype.drawPath = function(context) {
      var p, points, start, _i, _len, _results;
      points = this.points();
      start = points.shift();
      context.beginPath();
      context.moveTo(start.x, start.y);
      _results = [];
      for (_i = 0, _len = points.length; _i < _len; _i++) {
        p = points[_i];
        _results.push(context.lineTo(p.x, p.y));
      }
      return _results;
    };

    return LinearSpline;

  })();

  module.exports = LinearSpline;

}).call(this);
