// Generated by CoffeeScript 1.4.0
(function() {
  var Formattable, Geometry, Intersections, LinearSpline, Path, Point, Sourcable, Spline;

  Point = require('./point');

  Formattable = require('./mixins/formattable');

  Sourcable = require('./mixins/sourcable');

  Intersections = require('./mixins/intersections');

  Geometry = require('./mixins/geometry');

  Spline = require('./mixins/spline');

  Path = require('./mixins/path');

  LinearSpline = (function() {

    [Formattable('LinearSpline'), Sourcable('geomjs.LinearSpline', 'vertices', 'bias'), Geometry, Path, Intersections, Spline(1)].forEach(function(mixin) {
      return mixin.attachTo(LinearSpline);
    });

    function LinearSpline(vertices, bias) {
      this.initSpline(vertices, bias);
    }

    LinearSpline.prototype.points = function() {
      return this.vertices.concat();
    };

    LinearSpline.prototype.segments = function() {
      return this.vertices.length - 1;
    };

    LinearSpline.prototype.validateVertices = function(vertices) {
      return vertices.length >= 2;
    };

    LinearSpline.prototype.drawVerticesConnections = function() {};

    return LinearSpline;

  })();

  module.exports = LinearSpline;

}).call(this);
