// Generated by CoffeeScript 1.4.0
(function() {

  Math.degToRad = function(n) {
    return n * Math.PI / 180;
  };

  Math.radToDeg = function(n) {
    return n * 180 / Math.PI;
  };

}).call(this);
