// Generated by CoffeeScript 1.4.0
(function() {
  var Mixin;

  Mixin = (function() {

    function Mixin() {}

    Mixin.attachTo = function(klass) {
      var k, v, _ref, _results;
      _ref = this.prototype;
      _results = [];
      for (k in _ref) {
        v = _ref[k];
        _results.push(klass.prototype[k] = v);
      }
      return _results;
    };

    return Mixin;

  })();

  module.exports = Mixin;

}).call(this);
