// Generated by CoffeeScript 1.4.0
(function() {
  var Mixin, Parameterizable,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  Mixin = require('./mixin');

  Parameterizable = function(method, parameters, allowPartial) {
    if (allowPartial == null) {
      allowPartial = false;
    }
    return (function(_super) {

      __extends(_Class, _super);

      function _Class() {
        return _Class.__super__.constructor.apply(this, arguments);
      }

      _Class.included = function(klass) {
        var f;
        f = function() {
          var args, k, n, o, output, strict, v, _i;
          args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), strict = arguments[_i++];
          if (typeof strict === 'number') {
            args.push(strict);
            strict = false;
          }
          output = {};
          o = arguments[0];
          if ((o != null) && typeof o === 'object') {
            for (k in parameters) {
              output[k] = parseFloat(o[k]);
            }
          } else {
            n = 0;
            for (k in parameters) {
              v = parameters[k];
              output[k] = parseFloat(arguments[n++]);
            }
          }
          for (k in parameters) {
            v = parameters[k];
            if (isNaN(output[k])) {
              if (strict) {
                throw new Error("" + output + " doesn't match " + parameters);
              }
              if (allowPartial) {
                delete output[k];
              } else {
                output[k] = v;
              }
            }
          }
          return output;
        };
        klass[method] = f;
        return klass.prototype[method] = f;
      };

      return _Class;

    })(Mixin);
  };

  module.exports = Parameterizable;

}).call(this);
