// Generated by CoffeeScript 1.4.0
(function() {
  var Path;

  Path = (function() {

    function Path() {}

    Path.attachTo = function(klass) {
      var k, v, _ref, _results;
      _ref = Path.prototype;
      _results = [];
      for (k in _ref) {
        v = _ref[k];
        _results.push(klass.prototype[k] = v);
      }
      return _results;
    };

    Path.prototype.pathTangentAt = function(n, accuracy, pathBasedOnLength) {
      if (accuracy == null) {
        accuracy = 1 / 100;
      }
      if (pathBasedOnLength == null) {
        pathBasedOnLength = true;
      }
      return this.pathPointAt((n + accuracy) % 1).subtract(this.pathPointAt((1 + n - accuracy) % 1)).normalize(1);
    };

    return Path;

  })();

  module.exports = Path;

}).call(this);
