// Generated by CoffeeScript 1.4.0
(function() {
  var Formattable, Geometry, Intersections, Path, Point, QuadBezier, Sourcable, Spline, include;

  include = require('./include').include;

  Point = require('./point');

  Formattable = require('./mixins/formattable');

  Sourcable = require('./mixins/sourcable');

  Intersections = require('./mixins/intersections');

  Geometry = require('./mixins/geometry');

  Spline = require('./mixins/spline');

  Path = require('./mixins/path');

  QuadBezier = (function() {

    include([Formattable('QuadBezier'), Sourcable('geomjs.QuadBezier', 'vertices', 'bias'), Geometry, Path, Intersections, Spline(2)])["in"](QuadBezier);

    function QuadBezier(vertices, bias) {
      if (bias == null) {
        bias = 20;
      }
      this.initSpline(vertices, bias);
    }

    QuadBezier.prototype.pointInSegment = function(t, seg) {
      var pt;
      pt = new Point();
      pt.x = (seg[0].x * this.b1(t)) + (seg[1].x * this.b2(t)) + (seg[2].x * this.b3(t));
      pt.y = (seg[0].y * this.b1(t)) + (seg[1].y * this.b2(t)) + (seg[2].y * this.b3(t));
      return pt;
    };

    QuadBezier.prototype.b1 = function(t) {
      return (1 - t) * (1 - t);
    };

    QuadBezier.prototype.b2 = function(t) {
      return 2 * t * (1 - t);
    };

    QuadBezier.prototype.b3 = function(t) {
      return t * t;
    };

    return QuadBezier;

  })();

  module.exports = QuadBezier;

}).call(this);
