// Generated by CoffeeScript 1.4.0
(function() {
  var Formattable, Geometry, Intersections, Path, Point, QuintBezier, Sourcable, Spline, include;

  include = require('./include').include;

  Point = require('./point');

  Formattable = require('./mixins/formattable');

  Sourcable = require('./mixins/sourcable');

  Intersections = require('./mixins/intersections');

  Geometry = require('./mixins/geometry');

  Spline = require('./mixins/spline');

  Path = require('./mixins/path');

  QuintBezier = (function() {

    include([Formattable('QuintBezier'), Sourcable('geomjs.QuintBezier', 'vertices', 'bias'), Geometry, Path, Intersections, Spline(4)])["in"](QuintBezier);

    function QuintBezier(vertices, bias) {
      if (bias == null) {
        bias = 20;
      }
      this.initSpline(vertices, bias);
    }

    QuintBezier.prototype.pointInSegment = function(t, seg) {
      var pt;
      pt = new Point();
      pt.x = (seg[0].x * this.b1(t)) + (seg[1].x * this.b2(t)) + (seg[2].x * this.b3(t)) + (seg[3].x * this.b4(t)) + (seg[4].x * this.b5(t));
      pt.y = (seg[0].y * this.b1(t)) + (seg[1].y * this.b2(t)) + (seg[2].y * this.b3(t)) + (seg[3].y * this.b4(t)) + (seg[4].y * this.b5(t));
      return pt;
    };

    QuintBezier.prototype.b1 = function(t) {
      return (1 - t) * (1 - t) * (1 - t) * (1 - t);
    };

    QuintBezier.prototype.b2 = function(t) {
      return 4 * t * (1 - t) * (1 - t) * (1 - t);
    };

    QuintBezier.prototype.b3 = function(t) {
      return 6 * t * t * (1 - t) * (1 - t);
    };

    QuintBezier.prototype.b4 = function(t) {
      return 4 * t * t * t * (1 - t);
    };

    QuintBezier.prototype.b5 = function(t) {
      return t * t * t * t;
    };

    return QuintBezier;

  })();

  module.exports = QuintBezier;

}).call(this);
