// Generated by CoffeeScript 1.4.0
(function() {
  var Point, Rectangle;

  Point = require('./point');

  Rectangle = (function() {

    function Rectangle(x, y, width, height, rotation) {
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
      this.width = width != null ? width : 0;
      this.height = height != null ? height : 0;
      this.rotation = rotation != null ? rotation : 0;
    }

    Rectangle.prototype.topLeft = function() {
      return new Point(this.x, this.y);
    };

    Rectangle.prototype.topRight = function() {
      return new Point(this.x, this.y).add(this.topEdge());
    };

    Rectangle.prototype.bottomLeft = function() {
      return new Point(this.x, this.y).add(this.leftEdge());
    };

    Rectangle.prototype.bottomRight = function() {
      return new Point(this.x, this.y).add(this.topEdge()).add(this.leftEdge());
    };

    Rectangle.prototype.topEdge = function() {
      return new Point(this.width * Math.cos(Math.degToRad(this.rotation)), this.width * Math.sin(Math.degToRad(this.rotation)));
    };

    Rectangle.prototype.leftEdge = function() {
      return new Point(this.height * Math.cos(Math.degToRad(this.rotation) + Math.PI / 2), this.height * Math.sin(Math.degToRad(this.rotation) + Math.PI / 2));
    };

    Rectangle.prototype.bottomEdge = function() {
      return this.topEdge();
    };

    Rectangle.prototype.rightEdge = function() {
      return this.leftEdge();
    };


    Rectangle.prototype.acreage = function() {
      return this.width * this.height;
    };
    return Rectangle;

  })();

  module.exports = Rectangle;

}).call(this);
