// Generated by CoffeeScript 1.4.0
(function() {
  var Surface;

  Surface = (function() {

    function Surface() {}

    Surface.attachTo = function(klass) {
      var k, v, _results;
      _results = [];
      for (k in this) {
        v = this[k];
        if (k !== 'attachTo') {
          _results.push(klass.prototype[k] = v);
        }
      }
      return _results;
    };

    Surface.containsGeometry = function(geometry) {
      var _this = this;
      return geometry.points().every(function(point) {
        return _this.contains(point);
      });
    };

    return Surface;

  })();

  module.exports = Surface;

}).call(this);
