// Generated by CoffeeScript 1.4.0
(function() {
  var Surface;

  Surface = (function() {

    function Surface() {}

    Surface.attachTo = function(klass) {
      var k, v, _ref, _results;
      _ref = Surface.prototype;
      _results = [];
      for (k in _ref) {
        v = _ref[k];
        _results.push(klass.prototype[k] = v);
      }
      return _results;
    };

    Surface.prototype.containsGeometry = function(geometry) {
      var _this = this;
      return geometry.points().every(function(point) {
        return _this.contains(point);
      });
    };

    return Surface;

  })();

  module.exports = Surface;

}).call(this);
